package main.java.me.avankziar.mavec.spigot.cmdtree;

public enum CommandExecuteType
{
	MAVEC,
	MAVEC_MODIFIER,
	MAVEC_MODIFIER_LIST,
	MAVEC_MODIFIER_ADD,
	MAVEC_MODIFIER_REGISTERED,
	MAVEC_MODIFIER_REMOVE,
	MAVEC_VALUEENTRY,
	MAVEC_VALUEENTRY_LIST,
	MAVEC_VALUEENTRY_ADD,
	MAVEC_VALUEENTRY_REGISTERED,
	MAVEC_VALUEENTRY_REMOVE;
}
